name: 'Microsoft Teams Notification'
description: 'Send a custom notification message to a Microsoft Teams channel with GitHub repo details'
author: 'jdcargile'
branding:
  icon: message-circle
  color: purple 
inputs:
  github-token:
    description: 'GitHub Token'
    required: true 
  ms-teams-webhook-uri:
    description: 'Microsoft Teams Webhook URI'
    required: true 
  notification-summary:
    description: 'Message to be sent to Microsoft Teams channel'
    required: true 
  web-object-key:
    description: 'web object key related to web app, make sure to provide <build-number> placeholder inside notification-summary field'
    required: false
  notification-color:
    description: 'Color of notification header line'
    required: true 
  timezone:
    description: 'Timezone (ex. America/Denver)'
    required: false
  pr-number:
    description: 'Pull request number'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
