name: 'Microsoft Teams Notification'
description: 'Send a simple notification message to a Microsoft Teams channel'
author: 'jdcargile'
inputs:
  ms-teams-webhook-uri:
    description: 'Microsoft Teams Webhook URI'
    required: true
  message:
    description: 'Message to be sent to Microsoft Teams channel'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
